# Generated by Django 3.0.2 on 2021-01-07 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('predio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comprador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_cedula', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número de cédula comprador')),
                ('nombres', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombres')),
                ('apellidos', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellidos')),
                ('casado', models.BooleanField(blank=True, default=False, null=True, verbose_name='Casado')),
            ],
            options={
                'db_table': 'comprador',
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_cedula', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número de cédula vendedor')),
                ('nombres', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombres')),
                ('apellidos', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellidos')),
                ('casado', models.BooleanField(blank=True, default=False, null=True, verbose_name='Casado')),
            ],
            options={
                'db_table': 'vendedor',
            },
        ),
        migrations.CreateModel(
            name='Alcabala',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('numero', models.IntegerField(blank=True, null=True, verbose_name='Numero')),
                ('descripcion_tramite', models.TextField(blank=True, max_length=300, null=True, verbose_name='Descripcion del tramite')),
                ('valor_compra_venta', models.FloatField(blank=True, null=True, verbose_name='Valor de la compra-venta')),
                ('impuesto_alcabalas', models.FloatField(blank=True, null=True, verbose_name='Impuesto de alacabalas')),
                ('alcabalas_provinciales', models.FloatField(blank=True, null=True, verbose_name='Alcabalas provinciales')),
                ('fondos_escolares', models.FloatField(blank=True, null=True, verbose_name='Fondos escolares')),
                ('fondos_prevencion_riesgos', models.FloatField(blank=True, null=True, verbose_name='Fondos de prevencion de riesgos')),
                ('agua_potable', models.FloatField(blank=True, null=True, verbose_name='Agua potable')),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alcabala.Comprador')),
                ('predio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predio.Predio')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alcabala.Vendedor')),
            ],
            options={
                'db_table': 'alcabala',
            },
        ),
    ]
