# Generated by Django 3.0.2 on 2021-05-11 15:48

import apps.auditoria.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('direccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_cedula', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Número de cédula')),
                ('nombres', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombres')),
                ('apellidos', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellidos')),
                ('casado', models.BooleanField(blank=True, default=False, null=True, verbose_name='Casado')),
            ],
            options={
                'db_table': 'persona',
            },
            bases=(apps.auditoria.mixins.AuditMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Predio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clave_catastral', models.CharField(blank=True, max_length=25, null=True, verbose_name='Clave catastral')),
                ('avaluo_comercial', models.FloatField(blank=True, null=True, verbose_name='Avaluo comercial')),
                ('area_terreno', models.FloatField(blank=True, null=True, verbose_name='Área del terreno')),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='direccion.Direccion')),
            ],
            options={
                'db_table': 'predio',
            },
            bases=(apps.auditoria.mixins.AuditMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Alcabala',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('descripcion_tramite', models.TextField(blank=True, max_length=300, null=True, verbose_name='Descripcion del tramite')),
                ('valor_compra_venta', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, null=True, verbose_name='Valor de la compra-venta')),
                ('impuesto_alcabalas', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, null=True, verbose_name='Impuesto de alacabalas')),
                ('alcabalas_provinciales', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, null=True, verbose_name='Alcabalas provinciales')),
                ('fondos_escolares', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, null=True, verbose_name='Fondos escolares')),
                ('fondos_prevencion_riesgos', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, null=True, verbose_name='Fondos de prevencion de riesgos')),
                ('agua_potable', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, null=True, verbose_name='Agua potable')),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprador', to='alcabala.Persona')),
                ('predio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alcabala.Predio')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendedor', to='alcabala.Persona')),
            ],
            options={
                'db_table': 'alcabala',
            },
            bases=(apps.auditoria.mixins.AuditMixin, models.Model),
        ),
    ]
