# Generated by Django 3.0.2 on 2021-01-05 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alcabala', '0002_auto_20210105_1743'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='alcabala',
            table='alcabala',
        ),
        migrations.AlterModelTable(
            name='comprador',
            table='comprador',
        ),
        migrations.AlterModelTable(
            name='vendedor',
            table='vendedor',
        ),
    ]
