# Generated by Django 3.0.2 on 2021-03-13 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.CharField(blank=True, max_length=15, null=True, verbose_name='Texto')),
            ],
        ),
    ]
