# Generated by Django 3.0.2 on 2021-01-07 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoContribuyente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tipo de contribuyente ')),
                ('obligado_contabilidad', models.BooleanField(blank=True, default=False, null=True, verbose_name='Obligado a llevar contabilidad ')),
            ],
            options={
                'db_table': 'tipo_contribuyente',
            },
        ),
        migrations.CreateModel(
            name='Contribuyente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ruc', models.CharField(blank=True, max_length=13, null=True, verbose_name='Ruc ')),
                ('numero_cedula', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número de cédula')),
                ('nacionalidad', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nacionalidad')),
                ('nombres', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombres')),
                ('apellidos', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellidos')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='Email')),
                ('tlf_celular', models.CharField(blank=True, max_length=10, null=True, verbose_name='Celular')),
                ('tlf_convencional', models.CharField(blank=True, max_length=10, null=True, verbose_name='Telefono convencional')),
                ('tipocontribuyente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contribuyente.TipoContribuyente')),
            ],
            options={
                'db_table': 'contribuyente',
            },
        ),
    ]
