# Generated by Django 3.0.2 on 2021-01-16 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contribuyente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Juridico',
            fields=[
                ('contribuyente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contribuyente.Contribuyente')),
                ('razon_social', models.CharField(max_length=50, null=True, verbose_name='Razon social')),
                ('cedula_representante', models.CharField(max_length=10, null=True, verbose_name='Cédula del representante')),
                ('nombres_representante', models.CharField(max_length=50, null=True, verbose_name='Nombres del representante')),
                ('apellidos_representante', models.CharField(max_length=50, null=True, verbose_name='Apellidos del representante')),
                ('telefono_representante', models.CharField(max_length=10, null=True, verbose_name='Teléfono del representante')),
                ('correo_representante', models.EmailField(max_length=50, null=True, verbose_name='Correo del representante')),
            ],
            bases=('contribuyente.contribuyente',),
        ),
        migrations.CreateModel(
            name='Natural',
            fields=[
                ('contribuyente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contribuyente.Contribuyente')),
                ('numero_cedula', models.CharField(max_length=10, null=True, unique=True, verbose_name='Número de cédula')),
                ('nacionalidad', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nacionalidad')),
                ('nombres', models.CharField(max_length=50, null=True, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=50, null=True, verbose_name='Apellidos')),
            ],
            bases=('contribuyente.contribuyente',),
        ),
        migrations.AddField(
            model_name='contribuyente',
            name='estado',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Activo/Inactivo'),
        ),
        migrations.AlterField(
            model_name='contribuyente',
            name='ruc',
            field=models.CharField(max_length=13, null=True, unique=True, verbose_name='Ruc '),
        ),
        migrations.AlterField(
            model_name='tipocontribuyente',
            name='nombre',
            field=models.CharField(blank=True, choices=[('NATURAL', 'Natural'), ('JURIDICA', 'Jurídica')], max_length=20, null=True, verbose_name='Tipo de contribuyente '),
        ),
    ]
