# Generated by Django 3.0.2 on 2021-01-14 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribuyente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribuyente',
            name='numero_cedula',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Número de cédula'),
        ),
        migrations.AlterField(
            model_name='tipocontribuyente',
            name='nombre',
            field=models.CharField(blank=True, choices=[('NATURAL', 'Natural'), ('JURIDICA', 'Jurídica')], max_length=20, null=True, verbose_name='Tipo de contribuyente '),
        ),
    ]
