# Generated by Django 3.0.2 on 2021-01-05 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contribuyente', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contribuyente',
            old_name='n_cedula',
            new_name='numero_cedula',
        ),
    ]
