# Generated by Django 3.0.2 on 2021-01-05 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contribuyente', '0002_auto_20210105_1743'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contribuyente',
            table='contribuyente',
        ),
        migrations.AlterModelTable(
            name='tipocontribuyente',
            table='tipo_contribuyente',
        ),
    ]
