# Generated by Django 3.0.2 on 2021-01-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribuyente', '0002_auto_20210113_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribuyente',
            name='numero_cedula',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='Número de cédula'),
        ),
    ]
