# Generated by Django 3.0.2 on 2021-01-19 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribuyente', '0002_auto_20210116_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribuyente',
            name='estado',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Activo/Inactivo'),
        ),
        migrations.AlterField(
            model_name='tipocontribuyente',
            name='nombre',
            field=models.CharField(blank=True, choices=[('Natural', 'Natural'), ('Jurídica', 'Jurídica')], max_length=20, null=True, verbose_name='Tipo de contribuyente '),
        ),
    ]
