# Generated by Django 3.0.2 on 2021-01-19 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribuyente', '0003_auto_20210118_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juridico',
            name='correo_representante',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='Correo del representante'),
        ),
        migrations.AlterField(
            model_name='juridico',
            name='telefono_representante',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Teléfono del representante'),
        ),
        migrations.AlterField(
            model_name='natural',
            name='nacionalidad',
            field=models.CharField(blank=True, choices=[('Ecuatoriana', 'Ecuatoriana'), ('Colombiana', 'Colombiana'), ('Venezonalana', 'Venezonalana')], max_length=20, null=True, verbose_name='Nacionalidad'),
        ),
    ]
