# Generated by Django 3.0.2 on 2021-01-15 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribuyente', '0003_auto_20210115_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribuyente',
            name='ruc',
            field=models.CharField(max_length=13, null=True, unique=True, verbose_name='Ruc '),
        ),
    ]
