# Generated by Django 3.0.2 on 2021-01-15 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribuyente', '0004_auto_20210115_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribuyente',
            name='apellidos',
            field=models.CharField(max_length=50, null=True, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='contribuyente',
            name='nombres',
            field=models.CharField(max_length=50, null=True, verbose_name='Nombres'),
        ),
    ]
