# Generated by Django 3.0.2 on 2021-01-19 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribuyente', '0004_auto_20210118_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribuyente',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email'),
        ),
    ]
