# Generated by Django 3.0.2 on 2021-01-16 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contribuyente', '0005_auto_20210115_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sociedad',
            fields=[
                ('contribuyente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contribuyente.Contribuyente')),
                ('razon_social', models.CharField(max_length=10, null=True, verbose_name='Razon social')),
            ],
            bases=('contribuyente.contribuyente',),
        ),
    ]
