# Generated by Django 3.0.2 on 2021-01-07 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alcabala', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plusvalia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField(blank=True, null=True, verbose_name='Número de plusvalia')),
                ('fecha_tramite', models.DateField(blank=True, null=True, verbose_name='Fecha del tramite')),
                ('fecha_escritura', models.DateField(blank=True, null=True, verbose_name='Fecha de la escritura')),
                ('fecha_notaria', models.DateField(blank=True, null=True, verbose_name='Fecha de la notaria')),
                ('valor_escritura', models.FloatField(blank=True, null=True, verbose_name='Valor del predio')),
                ('valor_notaria', models.FloatField(blank=True, null=True, verbose_name='Valor de cuantia de la notaria')),
                ('precio_venta', models.FloatField(blank=True, null=True, verbose_name='Precio de venta')),
                ('precio_adquisicion', models.FloatField(blank=True, null=True, verbose_name='Precio de adquisición')),
                ('diferencia_bruta', models.FloatField(blank=True, null=True, verbose_name='Diferencia bruta')),
                ('rebaja_mejoras', models.FloatField(blank=True, null=True, verbose_name='Rebaja por mejoras')),
                ('diferenicia_neta', models.FloatField(blank=True, null=True, verbose_name='Diferencia neta')),
                ('tenencia', models.FloatField(blank=True, null=True, verbose_name='Tenencia')),
                ('base_rebajar_moneda', models.FloatField(blank=True, null=True, verbose_name='Base para rebajar moneda')),
                ('rebaja_desvalorizacion', models.FloatField(blank=True, null=True, verbose_name='Rebaja por desvalorización')),
                ('utilidad_imponible', models.FloatField(blank=True, null=True, verbose_name='Utilidad imponible')),
                ('alcabala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alcabala.Alcabala')),
            ],
            options={
                'db_table': 'plusvalia',
            },
        ),
    ]
