# Generated by Django 3.0.2 on 2020-12-30 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Impuesto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField(blank=True, null=True, verbose_name='Numero')),
                ('fraccion_basica', models.IntegerField(blank=True, null=True, verbose_name='Fraccion basica')),
                ('fraccion_excedente', models.IntegerField(blank=True, null=True, verbose_name='Fraccion excedente')),
                ('impuesto_fraccion_basica', models.IntegerField(blank=True, null=True, verbose_name='Impuesto fraccion basica')),
                ('porcentaje_fraccion_excedente', models.FloatField(blank=True, null=True, verbose_name='Porcentaje fraccion excedente')),
            ],
        ),
        migrations.CreateModel(
            name='Vencimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('digito', models.IntegerField(blank=True, null=True, verbose_name='Noveno dígito de cédula')),
                ('no_obligado', models.DateField(blank=True, null=True, verbose_name='No obligado')),
                ('obligado', models.DateField(blank=True, null=True, verbose_name='Obligado')),
            ],
        ),
    ]
