# Generated by Django 3.0.2 on 2021-05-11 15:48

import apps.auditoria.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Impuesto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField(null=True, verbose_name='Numero')),
                ('fraccion_basica', models.IntegerField(null=True, verbose_name='Fraccion basica')),
                ('fraccion_excedente', models.IntegerField(null=True, verbose_name='Fraccion excedente')),
                ('impuesto_fraccion_basica', models.IntegerField(null=True, verbose_name='Impuesto fraccion basica')),
                ('porcentaje_fraccion_excedente', models.DecimalField(decimal_places=5, default=0.0, max_digits=9, null=True, verbose_name='Porcentaje fraccion excedente')),
                ('estado', models.BooleanField(blank=True, default=True, null=True, verbose_name='Activo/Inactivo')),
            ],
            options={
                'db_table': 'impuesto',
            },
            bases=(apps.auditoria.mixins.AuditMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(null=True, verbose_name='Fecha')),
                ('porcentaje', models.DecimalField(decimal_places=5, default=0.0, max_digits=9, null=True, verbose_name='Porcentaje multa')),
                ('estado', models.BooleanField(blank=True, default=True, null=True, verbose_name='Activo/Inactivo')),
            ],
            options={
                'db_table': 'multa',
            },
            bases=(apps.auditoria.mixins.AuditMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Vencimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('digito', models.IntegerField(null=True, verbose_name='Noveno dígito de cédula')),
                ('no_obligado', models.DateField(null=True, verbose_name='No obligado')),
                ('obligado', models.DateField(null=True, verbose_name='Obligado')),
                ('estado', models.BooleanField(blank=True, default=True, null=True, verbose_name='Activo/Inactivo')),
            ],
            options={
                'db_table': 'vencimiento',
            },
            bases=(apps.auditoria.mixins.AuditMixin, models.Model),
        ),
    ]
