# Generated by Django 3.0.2 on 2021-01-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impuesto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impuesto',
            name='fraccion_basica',
            field=models.IntegerField(null=True, verbose_name='Fraccion basica'),
        ),
        migrations.AlterField(
            model_name='impuesto',
            name='fraccion_excedente',
            field=models.IntegerField(null=True, verbose_name='Fraccion excedente'),
        ),
        migrations.AlterField(
            model_name='impuesto',
            name='impuesto_fraccion_basica',
            field=models.IntegerField(null=True, verbose_name='Impuesto fraccion basica'),
        ),
        migrations.AlterField(
            model_name='impuesto',
            name='numero',
            field=models.IntegerField(null=True, verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='impuesto',
            name='porcentaje_fraccion_excedente',
            field=models.FloatField(null=True, verbose_name='Porcentaje fraccion excedente'),
        ),
        migrations.AlterField(
            model_name='multa',
            name='anio',
            field=models.CharField(max_length=4, null=True, verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='multa',
            name='mes',
            field=models.CharField(max_length=15, null=True, verbose_name='Mes'),
        ),
        migrations.AlterField(
            model_name='multa',
            name='porcentaje',
            field=models.FloatField(null=True, verbose_name='Porcentaje multa'),
        ),
        migrations.AlterField(
            model_name='vencimiento',
            name='digito',
            field=models.IntegerField(null=True, verbose_name='Noveno dígito de cédula'),
        ),
        migrations.AlterField(
            model_name='vencimiento',
            name='no_obligado',
            field=models.DateField(null=True, verbose_name='No obligado'),
        ),
        migrations.AlterField(
            model_name='vencimiento',
            name='obligado',
            field=models.DateField(null=True, verbose_name='Obligado'),
        ),
    ]
