# Generated by Django 3.0.2 on 2021-01-05 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impuesto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('anio', models.CharField(blank=True, max_length=4, null=True, verbose_name='Año')),
                ('mes', models.CharField(blank=True, max_length=15, null=True, verbose_name='Mes')),
                ('porcentaje', models.FloatField(blank=True, null=True, verbose_name='Porcentaje multa')),
            ],
        ),
    ]
