# Generated by Django 3.0.2 on 2021-01-05 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impuesto', '0002_multa'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='impuesto',
            table='impuesto',
        ),
        migrations.AlterModelTable(
            name='multa',
            table='multa',
        ),
        migrations.AlterModelTable(
            name='vencimiento',
            table='vencimiento',
        ),
    ]
