# Generated by Django 3.0.2 on 2021-03-13 20:33

import apps.auditoria.mixins
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contribuyente', '0001_initial'),
        ('establecimiento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_patente', models.IntegerField(blank=True, null=True, verbose_name='Número de patente')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('exonerada', models.BooleanField(blank=True, default=False, null=True, verbose_name='Patente exonerada')),
                ('suspendida', models.BooleanField(blank=True, default=False, null=True, verbose_name='Patente suspendida')),
                ('contribuyente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contribuyente.Contribuyente')),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establecimiento.Establecimiento')),
            ],
            options={
                'db_table': 'patente',
            },
            bases=(apps.auditoria.mixins.AuditMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DetallePatente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Fecha de tramite')),
                ('impuesto', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, null=True, verbose_name='Impuesto')),
                ('interes', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, null=True, verbose_name='Interes')),
                ('multa', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, null=True, verbose_name='Multa')),
                ('servicios_administrativos', models.DecimalField(decimal_places=2, default=0.99, max_digits=9, verbose_name='Servicios administrativos')),
                ('patente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patente.Patente')),
            ],
            options={
                'db_table': 'detalle_patente',
            },
            bases=(apps.auditoria.mixins.AuditMixin, models.Model),
        ),
    ]
