# Generated by Django 3.0.2 on 2021-01-07 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('establecimiento', '0001_initial'),
        ('contribuyente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_patente', models.IntegerField(blank=True, null=True, verbose_name='Número de patente')),
                ('exonerada', models.BooleanField(blank=True, default=False, null=True, verbose_name='Patente exonerada')),
                ('suspendida', models.BooleanField(blank=True, default=False, null=True, verbose_name='Patente suspendida')),
                ('contribuyente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contribuyente.Contribuyente')),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establecimiento.Establecimiento')),
            ],
            options={
                'db_table': 'patente',
            },
        ),
        migrations.CreateModel(
            name='DetallePatente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('zona', models.CharField(blank=True, max_length=10, null=True, verbose_name='Zona urbana o rural')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha de tramite')),
                ('impuesto', models.FloatField(blank=True, null=True, verbose_name='Impuesto')),
                ('interes', models.FloatField(blank=True, null=True, verbose_name='Interes')),
                ('multa', models.FloatField(blank=True, null=True, verbose_name='Multa')),
                ('servicios_administrativos', models.FloatField(blank=True, null=True, verbose_name='Servicios administrativos')),
                ('patente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patente.Patente')),
            ],
            options={
                'db_table': 'detalle_patente',
            },
        ),
    ]
