name: Django ERP Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      DB_ENGINE: django.db.backends.postgresql_psycopg2
      DB_NAME: jefaturatest
      DB_USER: test
      DB_PASSWORD: test1234
      DB_HOST: localhost
      DB_PORT: 5432
      HOST_EMAIL: smtp.gmail.com
      USER_EMAIL: jefaturatest@gmail.com
      USER_EMAIL_PASSWORD: MyStrangePassword1234
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Start PostgreSQL on Ubuntu
      run: |
        sudo systemctl start postgresql.service
        pg_isready
    - name: Create user test
      run: |
        sudo -u postgres psql --command="CREATE USER test PASSWORD 'test1234'" --command="\du"
    - name: Create jefaturatest database
      run: |
        sudo -u postgres createdb --owner=test jefaturatest
        PGPASSWORD=test1234 psql --username=test --host=localhost --list jefaturatest
    - name: Setup dbcreate permission
      run: |
        sudo -u postgres ALTER USER test CREATEDB
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Testing module patente
      run: |
        python3 manage.py test apps.patente.tests.test_models --verbosity 2
    - name: Testing module alcabala plusvalia
      run: |
        python 3 manage.py test apps.alcabala.tests --verbosity 2
    - name: Testing user module
      run: |
        python 3 manage.py test apps.usuario.tests --verbosity 2
