name: Django ERP Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Testing module patente
      run: |
        python3 manage.py test apps.patente.tests.test_models --verbosity 2
    - name: Testing module alcabala plusvalia
      run: |
        python 3 manage.py test apps.alcabala.tests --verbosity 2
    - name: Testing user module
      run: |
        python 3 manage.py test apps.usuario.tests --verbosity 2
