# Generated by Django 3.0.2 on 2021-05-11 15:48

import apps.auditoria.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('direccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoActividad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_actividad', models.CharField(choices=[('Comercial', 'Comercial'), ('Industrial', 'Industrial'), ('Inmobiliaria', 'Inmobiliaria'), ('Financiera', 'Financiera'), ('Artesanal', 'Artesanal'), ('Profesional', 'Profesional'), ('Alcoholes', 'Alcoholes')], max_length=25, null=True, verbose_name='Tipo de actividad comercial')),
            ],
            options={
                'db_table': 'tipo_actividad',
            },
            bases=(apps.auditoria.mixins.AuditMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=70, null=True, verbose_name='Nombre del establecimiento')),
                ('descripcion_actividad', models.TextField(blank=True, max_length=300, null=True, verbose_name='Descripcion actividad comercial')),
                ('fecha_inicio_actividad', models.DateField(null=True, verbose_name='Fecha de inicio de actividad comercial')),
                ('total_patrimonio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Total de patrimonio')),
                ('tipo_venta', models.CharField(choices=[('Venta al por mayor', 'Venta al por mayor '), ('Venta al por menor', 'Venta al por menor '), ('Venta al por mayor y menor', 'Venta al por mayor y menor')], max_length=35, null=True, verbose_name='Tipo de venta')),
                ('estado', models.BooleanField(blank=True, default=True, null=True, verbose_name='Activo/Inactivo')),
                ('situacion_legal', models.CharField(blank=True, choices=[('Propio', 'Propio'), ('Arrendado', 'Arrendado'), ('Anticresis', 'Anticresis')], max_length=15, null=True, verbose_name='Situación legal')),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='direccion.Direccion')),
                ('tipo_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establecimiento.TipoActividad')),
            ],
            options={
                'db_table': 'establecimiento',
            },
            bases=(apps.auditoria.mixins.AuditMixin, models.Model),
        ),
    ]
